# Generated by Django 4.2 on 2023-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Clientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('data_nascimento', models.IntegerField()),
                ('sexo', models.CharField(max_length=3)),
                ('rua', models.CharField(max_length=255)),
                ('numero_casa', models.IntegerField()),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('telefone2', models.IntegerField()),
            ],
        ),
    ]
