# Generated by Django 4.2 on 2023-04-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cad_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro_Clientes',
            new_name='Cad_Clientes',
        ),
    ]
