# Generated by Django 4.2 on 2023-05-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cad_Clientes', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
