# Generated by Django 4.2 on 2023-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cad_Clientes', '0005_alter_cad_clientes_bairro_alter_cad_clientes_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cad_clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cad_clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cad_clientes',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cad_clientes',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
